# <u> Use only those concepts which have been taught till now </u>

In [2]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [3]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [4]:
# Your code here
np.mean(random_integers[0:5,2:4])




286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [5]:
# Create the 10 points
x=np.random.randint(5,20,(10,2))
x

array([[19, 12],
       [10, 16],
       [ 7, 12],
       [10, 19],
       [ 5,  9],
       [ 7,  7],
       [ 5, 14],
       [16,  6],
       [ 5,  8],
       [ 6,  8]])

In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
import math
Euclidean=[]
manhattan=[]
p=[]
for i in range(10):
  for j in range(10):
    #p.append([tuple(x[i]),tuple(x[j])])
    a=(((x[i][0]-x[j][0])**2)+((x[i][1]-x[j][1])**2))
    b=math.sqrt(a)
    Euclidean.append(b)





    a=abs(x[i][0]-x[j][0])+abs(x[i][1]-x[j][1])
    manhattan.append(a)

Euclidean=np.array(list(zip(p,Euclidean)))
manhattan=np.array(list(zip(p,manhattan)))

print(Euclidean)
print(len(Euclidean))
print(manhattan)





In [9]:
def eucledian_distance(point1,point2):
    """Calculates and returns Eucledian Distance"""
    x1,y1=point1
    x2,y2=point2
    return round(((x2-x1)**2+(y2-y1)**2)**0.5,2)                                # calculating eucledian distance 

euclidean_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(eucledian_distance(x[i],x[j]))
    euclidean_distances.append(np.asarray(inner_llist))
euclidean_distances = np.asarray(euclidean_distances)
print(euclidean_distances)

[[ 0.    9.85 12.   11.4  14.32 13.   14.14  6.71 14.56 13.6 ]
 [ 9.85  0.    5.    3.    8.6   9.49  5.39 11.66  9.43  8.94]
 [12.    5.    0.    7.62  3.61  5.    2.83 10.82  4.47  4.12]
 [11.4   3.    7.62  0.   11.18 12.37  7.07 14.32 12.08 11.7 ]
 [14.32  8.6   3.61 11.18  0.    2.83  5.   11.4   1.    1.41]
 [13.    9.49  5.   12.37  2.83  0.    7.28  9.06  2.24  1.41]
 [14.14  5.39  2.83  7.07  5.    7.28  0.   13.6   6.    6.08]
 [ 6.71 11.66 10.82 14.32 11.4   9.06 13.6   0.   11.18 10.2 ]
 [14.56  9.43  4.47 12.08  1.    2.24  6.   11.18  0.    1.  ]
 [13.6   8.94  4.12 11.7   1.41  1.41  6.08 10.2   1.    0.  ]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here





# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..










#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below



